### ISSUE TITLE
Only users whose IP are in Nigeria pay in Naira while other country pay in dollar

### ISSUE THREAD

**Issue by Sylar-codex** [Sylar-codex/jum-jacket-create-react-app-#2]

**Comment by tedleyem** [comment]
is this true? can i test this now?

**Comment by Sylar-codex** [comment]
No, currently working on it.

**Comment by tedleyem** [comment]
any update on this?

**Comment by Sylar-codex** [comment]
I’m still working on it. Shouldn’t take this long at all, but I’ve hit so many unlucky obstacles.
